### ISSUE TITLE
A quick question about the usage of embeddings model

### ISSUE THREAD

**Issue by HelloWorldLTY** [serenayj/LLM_Embedding_Medical_ML#1]
Hi, thanks for your great work. I notice that in the classifeir file, it seems that the EmbeddingModel class is not defined:

https://github.com/serenayj/LLM_Embedding_Medical_ML/blob/d69b10c5916336184555278ce5b31170103a240b/embedding_classifiers.py#L51

Should we use openai get_embeddings rather than EmbeddingModel to access the embeddings of different models? Thanks.

**Comment by serenayj** [comment]
Yes, this embeddingmodel could be from API and huggingface library.

**Comment by HelloWorldLTY** [comment]
Ok, thanks a lot.
